### ISSUE TITLE
Move docs to testing-library.com/preact?

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/preact-testing-library#11]
Hey @antsmartian! Would you be interested in moving your docs to https://testing-library.com/preact? (Similar to https://testing-library.com/react and https://testing-library.com/cypress)

The site source is here: https://github.com/alexkrolick/testing-library-docs

I think it'd be pretty trivial to move things over.

What do you think? cc @alexkrolick

**Comment by antsmartian** [comment]
Hey @kentcdodds sure. Will do this in sometime. Thanks for letting me know!

**Comment by olpeh** [comment]
I might be able to start working on this. Hope it's ok? I plan creating a PR to `testing-library-docs`

**Comment by antsmartian** [comment]
@olpeh Sure, you can work on it. (sorry I was busy these days, can't pick it up myself).

**Comment by olpeh** [comment]
Should we use PReact.. or Preact..?

**Comment by kentcdodds** [comment]
`Preact`

**Comment by olpeh** [comment]
Opened a WIP PR: https://github.com/alexkrolick/testing-library-docs/pull/41
