### ISSUE TITLE
Preact X testing not working

### ISSUE THREAD

**Issue by JoviDeCroock** [testing-library/preact-testing-library#13]
* `react-testing-library` version: latest
* `node` version: 10.15.2
* `npm` (or `yarn`) version: 6.4.1

When testing the new Preact X API hooks it fails because `MessageChannel` is undefined. Should this repo provide a mock for that or? Don't really know where's the best spot to open this issue.

**Comment by JoviDeCroock** [comment]
When I polyfill MessageChannel I seem to hit the bump that executing a hook does not update anything in react-testing-library they expose something named `act`

**Comment by antsmartian** [comment]
Hey, could you please provide me an sample on what you are trying to do here?

**Comment by JoviDeCroock** [comment]
Well since a hook just like state puts an entry on the render queue it is impossible to test at this given point but I've taken this issue up with the preact team and providing compatability from this library will be as simple as just exporting this new helper function:

https://github.com/developit/preact/pull/1371

I'll make a PR here when it's that time

**Comment by antsmartian** [comment]
@JoviDeCroock Thank you so much! I would be happy to accept a PR from your side :)

**Comment by mihar-22** [comment]
@JoviDeCroock migrating to `@testing-library/preact` and going through the readme should resolve your issue. I'm closing it for now but I'll reopen if your problems persist.
