### ISSUE TITLE
Join testing-library org?

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/preact-testing-library#18]
Hi 👋 would you like to join @testing-library and move this over to that org? May help make this more official and you could also rename the module to `@testing-library/preact` if you're interested. Let me know!

**Comment by paulchaplin** [comment]
As a user of this project, I'm hugely in favour of that -- partly from an ease-of-discovery point of view, but also because I think it would encourage more independent contributions. Thanks to @antsmartian for everything so far, in any case!

**Comment by kentcdodds** [comment]
Ping. Would you like some help @antsmartian?

**Comment by antsmartian** [comment]
@kentcdodds Sorry, was completely busy with my works. I will be moving this by next week for sure!

**Comment by tiagodreis** [comment]
What's the status on this? Any update @antsmartian  ? Thanks!

**Comment by antsmartian** [comment]
@kentcdodds I tried to transfer this project as it is to `testing-library`. But I got the following error: 
`You don’t have the permission to create repositories on testing-library`. Not sure, what is the mistake here.

**Comment by antsmartian** [comment]
@kentcdodds I have given you the collaborator access to this repo. I believe, now you should be able to transfer this to `testing-library`. I would love to be part of that as well :)

**Comment by kentcdodds** [comment]
Just added you. You should be able to transfer it

**Comment by antsmartian** [comment]
@kentcdodds Thanks. Transferred. (Sorry for making it so long, given the fact its so simple). Happy to be part of `@testing-library` 🎉 🎉 🎉 🎉

**Comment by kentcdodds** [comment]
Great! Would you like to publish `preact-testing-library` as `@testing-library/preact`? If so, I'll add you to the npm org and you can [follow what I did](https://github.com/testing-library/dom-testing-library/issues/260) for my libraries.

**Comment by antsmartian** [comment]
@kentcdodds I would be happy to. Can you please add me to the npm org, then will follow up on the instructions and do a npm publish.

**Comment by kentcdodds** [comment]
I'd prefer to see a little more movement on #19 before we start publishing to the `@testing-library` scope. Also, I think it would be wise to have Rahim join as a co-maintainer of the package as it seems like you're not able to be as responsive as some of the community would like.

**Comment by antsmartian** [comment]
@kentcdodds Totally agree. I would close that thread with the recent changes of Rahim. Then we can take this forward.

**Comment by mihar-22** [comment]
Closing this since we've already moved ahead in #19.
