### ISSUE TITLE
Possible collaboration?

### ISSUE THREAD

**Issue by mihar-22** [testing-library/preact-testing-library#19]
**Problem description**

I rewrote a new version of preact-testing-library that's up-to-date and inline with the react version. It includes tests, documentation and support for Hooks by wrapping all rendering and events with the `act` test utility. 

**Library differences**

Repository is here: [preact-testing-library](https://github.com/mihar-22/preact-testing-library)

- Supports Preact X but I think it should be pretty easy to add support for Preact 8.x+. Only difference I believe is that `act` is not available in 8.x and possibly `hydrate`.
- My library doesn't include `debounceRenderingOff` and `flushPromises`. Easy to add in for backwards support.
- More argument/return values for render function. Only additive, no issues.
- Adds automatic cleanups. No issues.
- Adds new `fireEvent` export. No issues.
- Exports `@testing-library/dom` with the `dtl` alias. Will cause issues and needs a solution. It was causing problems with rollup cjs bundling.
- Build tools and everything are different but this won't cause any issues. It still uses Travis CI and semantic releases. The script commands that matter are the same like `setup`and `validate`.

**Suggested solution**

Solve issues above and merge my library into this one and I can help with maintaining it. 

Either way I thought I'd leave it as a suggestion here. If there's any issues then no worries, I can also just keep a separate library available for anyone who needs it.

**Comment by kentcdodds** [comment]
I'm definitely in favor of a collaboration, but I'm not a maintainer of Preact Testing Library. What do you think @antsmartian?

**Comment by kentcdodds** [comment]
Also, I don't think `flushPromises` is necessary. The lib should just re-export all utilities from DOM Testing Library and those should be enough.

**Comment by antsmartian** [comment]
@kentcdodds I'm happy to accept any improvements from @mihar-22. Yeah, we should be using utils from DOM as you had mentioned, the code to be honest is bit outdated.

**Comment by mihar-22** [comment]
Hm, so when I remove the dtl alias I get this error: 

`TypeError: Cannot set property fireEvent of [object Object] which has only a getter`

It has to do with the re-exporting of `@testing-library/dom` but I'm not sure but if it's related to Rollup or Babel.

 May be related to https://github.com/apollographql/apollo-client/issues/4843#issuecomment-495717720?

**Comment by mihar-22** [comment]
Actually I just tested importing the bundles in from `@testing-library/react` and none of those work either. I get this error:

`TypeError: Cannot read property 'hasOwnProperty' of undefined`

It's failing because of the re-export and Rollup incorrectly handling it.

See this similar issue: https://github.com/apollographql/apollo-client/issues/4843#issuecomment-495717720

Is there any reason to have bundles? The import works just fine when I transpile it with `@babel/cli`. I could create the bundles with Babel plugins but not sure if it's needed.

**Comment by mihar-22** [comment]
For now I've just transpiled it using Babel and I can add bundles when someone needs it. Let me know how you'd like me to proceed with merging.

**Comment by alxclark** [comment]
Any progress on the issue ? @mihar-22 @antsmartian 

Super interested about using `preact-testing-library` with Preact X.

I'd be open to help if needed 👀

**Comment by mihar-22** [comment]
Hey @alxclark, I'm just not sure what to do because the library is outdated, a lot of parts in the package.json and other areas still address react-testing-library, and the build tools need a refresh too such as adding in codecov etc. I think the easiest thing for me is to make this point to my repo or merge my library into this one and overwrite everything. Not sure if there's a better way, but that'd be the easiest for me right now. Just waiting for a response from @antsmartian.

**Comment by kentcdodds** [comment]
If we don't hear anything from the maintainer soon, then I'll go ahead and facilitate your plan. We're all busy 😅

**Comment by antsmartian** [comment]
@mihar-22 I'm fine with the approach. May be if you can open up a PR, we can review it. Over-riding (might not work out) everything we need to check because it has around 800+ downloads per week. So I think we should be careful here.

**Comment by mihar-22** [comment]
**Update**

I forked and completed the library update here:

https://github.com/mihar-22/testing-library-preact/tree/pr/preact-next

However, I won't be able to make a pull request because I had to rebase old commits since they weren't following proper commit message conventions. I could create another fork and add my commits on top but I'll have to rebase the commits eventually regardless, since they effect CI and semantic releases.

Now this does mean the commit history is different but I don't think it'll affect anyone at this point. The library is not actively maintained or worked on by the community so I think in this particular case we can just simply override the repo completely. @antsmartian can pull the forked repo down and do a forced push, or give me privileges and I can do it.

**Releasing New Library**

How we release depends on if we're publishing under the @testing-library scope or not. 

If we are not then simply I do a major update and deprecated notice on my library, and we can do a dist tag for the next release of this lib just like Preact does. Following their lead from 8.x to 10.x we can use the dist tag @next.

If we are publishing under the @testing-library scope then we do major updates and deprecation notices on both old libs and just publish the new lib under the new scope.

**CI + Codecov Setup**

I won't be able to set these up unless I'm added in as a co-maintainer or whatever that gives me sufficient privileges.

**Comment by antsmartian** [comment]
@mihar-22 This sounds good. We can onboard you here and you can do the force push. I guess git history doesn't make sense, and its ok to replace with your commits. @kentcdodds: I tried to add him as maintainer for this project, but I couldn't able to find any links. Would you mind adding him? @mihar-22 Welcome to the team 🎉 🎉 🎉 🎉

**Comment by kentcdodds** [comment]
Just added @mihar-22 to the org. Once you have the repo in a good position, then I'll add you both to the npm org so you can publish under the `@testing-library` scope. Looking forward to it!

**Comment by mihar-22** [comment]
Thanks alot @antsmartian and @kentcdodds. I've finished pushing the library and doing some cleanup. Once we're added to the npm org we can publish the new library and deprecate the old ones. It's probably a good idea to keep @antsmartian old lib (preact-testing-library) incase anyone needs it for Preact 8.x.

**Comment by kentcdodds** [comment]
I recommend doing the same thing that we did with the other packages. The current preact-testing-library version will never go away, but anyone who install it not knowing about the change should be notified which is why we published a major version of the other packages with a deprecation warning. You can learn more about it all here: https://www.youtube.com/watch?v=BN5ELGSV25Q

I'll get both of you added to the npm org :)

**Comment by kentcdodds** [comment]
Let me know if you need any help getting things going. You're both on the npm org now :)

**Comment by mihar-22** [comment]
All done, I've published @testing-library/preact 🎉.

I deprecated and archived my old library: https://github.com/mihar-22/preact-testing-library.

In regards to deprecating @antsmartian you can do the following:

*Note: Since your old repo redirects here anyway you don't need to make any commits or push any changes to GitHub, you'll just need to update your NPM package.*

1. Add a warning in the readme that the library is deprecated and has moved.
2. Add a postinstall script that logs a warning (see above repo or commit as reference).
3. Publish a major release.
4. Run the following `npm deprecate preact-testing-library "Package has moved to the official testing-library org, please install @testing-library/preact"`.

I think that should be about it, once you're done we can close this issue.

**Comment by antsmartian** [comment]
@mihar-22 I have deprecated the package. (https://www.npmjs.com/package/preact-testing-library).

**Comment by antsmartian** [comment]
Also added the scripts to log a warning. I guess we are good to close this issue. Thanks. I would love to see the new changes as a PR instead of direct commits. So that everyone can aware of what changes going in. Hope that should be fine. @mihar-22. Thanks for your nice work! 🎉 🎉 🎉

**Comment by mihar-22** [comment]
Awesome thanks @antsmartian. I don't intend on pushing any other commits directly, it was just some final post cleaning. Closing the issue now :)
