### ISSUE TITLE
Working with preact/compat

### ISSUE THREAD

**Issue by lakshyaranganath** [testing-library/preact-testing-library#24]
- `preact-testing-library` version: 1.0.2
- `preact` version: 10.4.4
- `node` version: 12.16.3
- `npm` (or `yarn`) version: yarn 1.22.4

**Relevant code or config**
```
// jest.config.js
moduleNameMapper: {
    '^react$': 'preact/compat',
    '^react-dom/test-utils$': 'preact/test-utils',
    '^react-dom$': 'preact/compat',
    '^@testing-library/react$': '@testing-library/preact',
```
**What you did:**
Tried to alias `@testing-library/react` to `@testing-library/preact` because we're aliasing `react` and `react-dom` to `preact/compat`.

**What happened:**
Fails with an error that it cannot find waitFor, but I also suspect there may be other differences in the api's of both the libraries.

Reproduction repository:

Problem description:
We'd like our jest tests to run against preact and not react as long as we are using the `preact/compat` alias so that we know our tests(and hence implementations) work in preact.

Suggested solution:
Firstly, update the `@testing-library/dom` package to the latest version, and secondly, match any other mismatches in the library apis.

**Comment by kentcdodds** [comment]
Cc @mihar-22, would you like some help with getting this project going again?

**Comment by mihar-22** [comment]
No problem @kentcdodds, I'll sort it out this weekend.

**Comment by kentcdodds** [comment]
If you'd like, using `kcd-scripts` helps several of the other packages not worry about keeping tooling up-to-date. I can help you get that added, or you can reference some of the other Testing Library packages to get an idea for how that works.

kcd-scripts has built-in support for preact. All you need to do is:

1. Have preact as a dep
2. Use the `--p-react` flag with the build script when bundling

I'd suggest the build here be similar to React Testing Library: https://github.com/testing-library/react-testing-library/blob/499cc0449b46421c922d81ade986cce7628a8d05/package.json#L12-L16

It'd probably be something like this:

```javascript
    "prebuild": "rimraf dist",
    "build": "npm-run-all --parallel build:main build:bundle:main build:bundle:pure",
    "build:bundle:main": "dotenv -e .bundle.main.env kcd-scripts build -- --bundle --no-clean",
    "build:bundle:pure": "dotenv -e .bundle.main.env -e .bundle.pure.env kcd-scripts build -- --bundle --no-clean --p-react",
    "build:main": "kcd-scripts build --no-clean",
```

If you'd rather not use `kcd-scripts` that's totally fine too :)

**Comment by lakshyaranganath** [comment]
Hey team, thanks for looking into this, I see a PR merged for kcd-scripts, does that mean it will be integrated into this library soon? or does that mean I can just directly use testing-library/react for preact too?

**Comment by mihar-22** [comment]
Hey @lakshyaranganath, I'm just some bouncing between different work at the moment. I'll dig into it now and see how it goes.

**Comment by lakshyaranganath** [comment]
No problem, thanks @mihar-22. 👍

**Comment by mihar-22** [comment]
Migrating over to `kcd-scripts` causes `ReferenceError: React is not defined` and I can't find where it's coming from. The error is too obscure but mainly points to the libraries `render` function.  I've been banging my head for the last hour. 

The tests pass with the current build tools but I can't see any real difference between them and `kcd-scripts`. Do you have any idea why this might be happening @kentcdodds. It's all standard setup and I copied the `react-testing-library` to the tee. I added `BUILD_PREACT=true` to `.bundle.main.env`. I also added the following to the test command `cross-env BUILD_PREACT=true kcd-scripts test`.

**Comment by kentcdodds** [comment]
I have a feeling it should be `Preact.h` instead of `React.h` in the Babel config. You should be able to test that out locally.

**Comment by mihar-22** [comment]
Nah that can't be the issue because I don't have `react` installed so it's using the `h` pragma anyway. I tested it anyway and it didn't work.

**Comment by mihar-22** [comment]
Lost my mind ... but I finally found it. It's this line in the Jest configuration `transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$']`. I don't exactly know why yet but it works once I remove it.

**Comment by lakshyaranganath** [comment]
Hey @mihar-22, just checking in to see if theres been any changes or updates since your last comment :)

**Comment by mihar-22** [comment]
Hey @lakshyaranganath, no I haven't had a chance too. It's too late tonight to do it. I was planning on doing it tomorrow night but I don't have any definite timeline for you. I'll do my best tomorrow to have it ready and sorry for the delay.

**Comment by lakshyaranganath** [comment]
Hey @mihar-22, No problem at all, I understand. Thanks for the update :)

**Comment by mihar-22** [comment]
I think everything should work now @lakshyaranganath :) Keeping the open issue so you can report back if there's any issues. Sorry for the delay again.

**Comment by lakshyaranganath** [comment]
Awesome, i'll try this out today, appreciate it :)

**Comment by mihar-22** [comment]
Assuming everything is working and closing this issue. I'll reopen if issues persist.

**Comment by mischa-s** [comment]
Hi @whilelucky / @mihar-22 - I ran into this today. With this change what configuration is required in order to get this working?

I am using 

```
environment.config.resolve.alias = {
    'react': 'preact/compat',
    'react-dom/test-utils': 'preact/test-utils',
    'react-dom': 'preact/compat', // Must be below test-utils
    'react/jsx-runtime': 'preact/jsx-runtime'
  };
```

When I try to run my tests I receive 

`Cannot find module 'react/jsx-runtime'`

Thanks!

**Comment by mischa-s** [comment]
Uggghh. A classic "return to it later, problem is obvious". For anybody stumbling on this in the future I had not added the Jest config ( I went with https://github.com/preactjs/jest-preset-preact).
