### ISSUE TITLE
queryByText where string starts/ends with space returns null

### ISSUE THREAD

**Issue by dandro** [testing-library/preact-testing-library#39]
- `@testing-library/preact` version: 2.0.1
- `preact` version: 10.5.13
- `node` version: v14.15.1
- `yarn` version: 1.22.10

**Relevant code or config**

```
// title.tsx
type TitleProps = {
  title?: string;
};

export function Title({ title }: TitleProps) {
  return (
    <div>
      <h2 data-e2e="title">{title || `No title`}</h2>
    </div>
  );
}

// title.spec.tsx
import { Title } from './title';
import { render } from '@testing-library/preact';

describe(Title.name, () => {
  it('should display title when it starts with space', () => {
    const title = ' Some sick title';
  
    const { queryByText } = render(<Title title={title} />);
  
    expect(queryByText(title)).not.toBeNull();
  });
});
```

**What you did:**

Run the test above.

**What happened:**

Calling `queryByText(title)` returns null when title starts or ends with space. 

Problem description:

When using queryByText and the string I am searching for starts or ends with space, the result will be null. If I print the content  of the container

```
const { queryByText, container } = render(<Title title={title} />);

console.log(container.innerHtml);

```

The console shows the expected output `<div><h2 data-e2e="title"> Some sick title</h2></div>`. It works perfectly fine if I trim the string I am searching for. (e.g. `expect(queryByText(title.trim())).not.toBeNull();` will pass)

**Comment by mikerob215** [comment]
The second argument to `queryByText` needs to be `{ trim: false }`, otherwise dom testing library will trim the text content of the element and your text wont match.

**Comment by JoviDeCroock** [comment]
Closing this as resolved due to the above comment
