### ISSUE TITLE
🐛 onChange Event Misfiring

### ISSUE THREAD

**Issue by bayleedev** [testing-library/preact-testing-library#43]
🐛 Bugs:
  File an issue for bugs, missing documentation, or unexpected behavior.

- `preact-testing-library` version: v2.0.1
- `preact` version: v10.5.5
- `node` version: v14.15.5
- `npm` version: v6.14.11

**What you did:**

**What happened:**

The `fireEvent.change` didn't decorate the event the necessary way.

Reproduction repository:

https://github.com/bayleedev/preact-change-issue

Problem description:

This is what [the docs](https://preactjs.com/guide/v10/preact-testing-library) suggest trying

```diff
// test.js:36
-  if (false) {
+ {
    const field = await screen.getByRole('textbox', { name: 'Comment Body' });
    fireEvent.change(field, {
      value: 'user123', // the docs just suggest setting this one
    });
    expect(field.value).toEqual('user123'); // Received: "default_value"
  }
```

Suggested solution:

I made a few modifications to get it working, but it's reaching in kinda deep:

```javascript
// test.js:44
  // Change, working
  {
    const field = await screen.getByRole('textbox', { name: 'Comment Body' });
    const changeEvent = createEvent.change(field, {
      value: 'user123', // BROKE, possibly decorated in the library
      target: { value: 'user234' }, // ADD
    });
    changeEvent.inputType = 'insertText'; // ADD, required to get it to work
    await act(() => {
      return field.l.inputfalse(changeEvent);
      // return field.dispatchEvent(changeEvent) // DEL, this didn't work
    });
    // Assertion
    const textarea = screen.getByRole('textbox', { name: 'Comment Body' });
    expect(textarea.value).toEqual('on_change_value'); // SUCCESS!

    // Double assertion, to see if `body` was updated.
    const bodyData = screen.getByTestId('body-data');
    expect(bodyData.textContent).toEqual('on_change_value'); // SUCCESS!
  }
```

**Comment by bayleedev** [comment]
As a work around I used `onInput` and `fireEvent.input`.

**Comment by mikerob215** [comment]
I know this is a little late but you need to pass:
```javascript
{
  target: {
    value: 'user123'
  }
}
```
The event is firing but the value just wasnt set right.

**Comment by JoviDeCroock** [comment]
Closing this because of the solution provided by @mikerob215, thank you!
