### ISSUE TITLE
feat: add `renderHook`

### ISSUE THREAD

**Issue by MichaelDeBoey** [testing-library/preact-testing-library#52]
Just like `@testing-library/react` did in https://github.com/testing-library/react-testing-library/pull/991

CC/ @testing-library/preact

**Comment by JoviDeCroock** [comment]
Would that be [this implementation](https://github.com/testing-library/preact-hooks-testing-library/blob/main/src/renderHook.tsx)? Currently it looks like this is split across two repositories

**Comment by MichaelDeBoey** [comment]
@JoviDeCroock It is indeed moving the hook from `@testing-library/preact-hooks` (and deprecating the package) to `@testing-library/preact`
