### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by justinwilaby** [testing-library/preact-testing-library#53]
It's been 3 years since the last meaningful commits to `master`, PRs that fix critical defects remain unmerged and new issues are left unattended for weeks or months. This appears to have all the signs of a dead project. 

Are there plans to transfer ownership to new maintainers?

**Comment by oteoe** [comment]
@antsmartian  @mihar-22 @kentcdodds @nickmccurdy 

Hi Maintainers, could you just merge:
https://github.com/testing-library/preact-testing-library/pull/32

it's already been approved and a blocker for a lot of users.

Thank you

**Comment by kentcdodds** [comment]
Commented.

**Comment by justinwilaby** [comment]
Closing as this project is back under regular maintenance.
